[package]
name = "hashcash-randomx-sys"
description = "FFI bindings for RandomX"
license = "GPL-3.0-or-later"
version = "2.9.0"
authors = ["Wei Tang <wei@that.world>"]
edition = "2021"

[build-dependencies]
bindgen = "0.69.2"
cmake = "0.1.50"
