[package]
name = "p2pool-client-consensus"
authors = ["Hisaishi Joe <hisaishi@tuta.io>"]
edition.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures.workspace = true
jsonrpsee = { workspace = true, features = ["http-client"] }
log.workspace = true
parity-scale-codec = { workspace = true, features = ["std"] }
parking_lot.workspace = true
rand.workspace = true
thiserror.workspace = true

sc-client-api.workspace = true
sc-consensus-pow.workspace = true
sp-api = { workspace = true, features = ["std"] }
sp-core = { workspace = true, features = ["std"] }
sp-consensus-pow.workspace = true
sp-runtime = { workspace = true, features = ["std"] }

hashcash-client-consensus.workspace = true
hashcash-client-consensus-rpc.workspace = true
hashcash-primitives-core = { workspace = true, features = ["std"] }
hashcash-randomx.workspace = true
